//FOR LOGIN AXIOS POST REQUEST
export const LOGIN_INPUT_CHANGE = "LOGIN_INPUT_CHANGE";
export const POST_LOGIN_START = "POST_LOGIN_START";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
// export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR'
export const POST_CLEAR_LOGIN = "POST_CLEAR_LOGIN";

//REGISTER USER

export const REGISTER_INPUT_CHANGE = "REGISTER_INPUT_CHANGE";
export const POST_REGISTER_START = "POST_REGISTER_START";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
// export const POST_REGISTER_ERROR = 'POST_REGISTER_ERROR'
export const POST_CLEAR_REGISTER = "POST_CLEAR_REGISTER";

//GET ALL JOURNALS: JOURNAL LIST

export const GET_ALLJOURNALS_START = "GET_ALLJOURNALS_START";
export const GET_ALLJOURNALS_SUCCESS = "GET_ALLJOURNALS_SUCCESS";
// export const GET_ALLJOURNALS_ERROR = 'GET_ALLJOURNALS_ERROR'

//GET INDIVIDUAL JOURNAL: JOURNAL PAGE

export const GET_ONEJOURNAL_START = "GET_ONEJOURNAL_START";
export const GET_ONEJOURNAL_SUCCESS = "GET_ONEJOURNAL_SUCCESS";
// export const GET_ONEJOURNAL_ERROR = 'GET_ONEJOURNAL_ERROR'

//ADDING NEW JOURNAL POST TO EXISITNG JOURNALS

export const POST_JOURNAL_START = "POST_JOURNAL_START";
export const POST_JOURNAL_SUCCESS = "POST_JOURNAL_SUCCESS";

//INPUT CHANGE HANDLER FOR ADDING NEW JOURNAL

export const ADDING_INPUT_CHANGE = "ADDING_INPUT_CHANGE";

//DELETING A JOURNAL

export const DELETING_JOURNAL_START = "DELETING_JOURNAL_START";
export const DELETING_JOURNAL_SUCCESS = "DELETING_JOURNAL_SUCCESS";

//Updating/Editing Journal

export const EDIT_JOURNAL_START = "EDIT_JOURNAL_START";
export const EDIT_JOURNAL_SUCCESS = "EDIT_JOURNAL_SUCCESS";

//INPUT CHANGE HANDLER FOR EDITING JOURNAL

export const EDITING_JOURNAL_CHANGE = "EDITING_JOURNAL_CHANGE";
