
//FOR LOGIN AXIOS POST REQUEST
export const LOGIN_INPUT_CHANGE = "LOGIN_INPUT_CHANGE";
export const POST_LOGIN_START = 'POST_LOGIN_START'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR'
export const POST_CLEAR_LOGIN = 'POST_CLEAR_LOGIN'