//FOR ALL FORMS
export const INPUT_CHANGE = "INPUT_CHANGE";

//FOR LOGIN AXIOS POST REQUEST
export const POST_LOGIN_START = 'POST_LOGIN_START'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR'